name: Auto commit
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 7,8,9,10,11 * * *"
jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
